language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=weak_vendors
    - COMPOSER_MEMORY_LIMIT=-1

stages:
  - test

matrix:
  fast_finish: true
  include:
    - stage: test
      php: 7.1
    - stage: test
      php: 7.2
    - stage: test
      php: 7.3

install:
  - composer install

script:
  - vendor/bin/phpunit

notifications:
  email: oskarstark@googlemail.com
