language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=weak_vendors
    - COMPOSER_MEMORY_LIMIT=-1

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php:
      - nightly

install:
  - composer install

script:
  - vendor/bin/phpunit

notifications:
  email: oskarstark@googlemail.com
